// Dev config signer — mirrors the offline production signing runbook.
//
// Usage: dart run tool/sign_config.dart
//
// Generates (or reuses) an Ed25519 dev keypair in tool/dev_key.json,
// signs assets/configs/menu_configs.json byte-for-byte, writes the
// signature to assets/configs/menu_configs.sig, and pins the public key
// in lib/ussd/pinned_keys.dart.
//
// tool/dev_key.json is a DEVELOPMENT key. The production private key is
// kept in an offline signer and never enters this repository.

import 'dart:convert';
import 'dart:io';

import 'package:cryptography/cryptography.dart';

Future<void> main() async {
  final ed25519 = Ed25519();
  final keyFile = File('tool/dev_key.json');

  SimpleKeyPair keyPair;
  if (keyFile.existsSync()) {
    final saved = jsonDecode(keyFile.readAsStringSync()) as Map<String, dynamic>;
    keyPair = SimpleKeyPairData(
      base64Decode(saved['private'] as String),
      publicKey: SimplePublicKey(
        base64Decode(saved['public'] as String),
        type: KeyPairType.ed25519,
      ),
      type: KeyPairType.ed25519,
    );
  } else {
    keyPair = await ed25519.newKeyPair();
    final priv = await keyPair.extractPrivateKeyBytes();
    final pub = (await keyPair.extractPublicKey()).bytes;
    keyFile.writeAsStringSync(const JsonEncoder.withIndent('  ').convert({
      'comment': 'DEV ONLY signing key — never use in production',
      'private': base64Encode(priv),
      'public': base64Encode(pub),
    }));
    stdout.writeln('Generated new dev keypair at tool/dev_key.json');
  }

  final config = File('assets/configs/menu_configs.json').readAsBytesSync();
  final signature = await ed25519.sign(config, keyPair: keyPair);
  File('assets/configs/menu_configs.sig')
      .writeAsStringSync(base64Encode(signature.bytes));

  final pubB64 = base64Encode((await keyPair.extractPublicKey()).bytes);
  File('lib/ussd/pinned_keys.dart').writeAsStringSync('''
/// Public key pinned in the app binary for menu-config verification (§6.5).
///
/// DEV KEY ONLY — regenerated by `dart run tool/sign_config.dart`.
/// The production key lives in an offline signer; its private half is
/// never committed. Rotate via a signed kill-switch config, never in place.
const pinnedConfigPublicKeyB64 = '$pubB64';
''');

  stdout.writeln('Signed menu_configs.json -> menu_configs.sig');
  stdout.writeln('Pinned public key: $pubB64');
}
