/// Public key pinned in the app binary for menu-config verification (§6.5).
///
/// DEV KEY ONLY — regenerated by `dart run tool/sign_config.dart`.
/// The production key lives in an offline signer; its private half is
/// never committed. Rotate via a signed kill-switch config, never in place.
const pinnedConfigPublicKeyB64 = 'czzBvR7nMO1wxYp8uqMR762yxwKLQPWqgG/Cm8c23NM=';
